import { constantize, key2val, toArr, getBits, setEnumValue } from '../enum/base'
// PS: 模块类型和表格类型的key请不要设置成相同的

// 模块类型
const moduleTypeEnum = {
  CONTRACT: { L: '合同及项目表单', K: 'CONTRACT' },
  CONT_CENTER: { L: '成本中心表单', K: 'CONT_CENTER' },
  SUPPLIER: { L: '供应商表单', K: 'SUPPLIER' },
  MES_LOGISTICS: { L: 'MES-物流表单', K: 'MES_LOGISTICS' },
  WMS_LOGISTICS: { L: 'WMS-物流表单', K: 'WMS_LOGISTICS' },
  // STEEL_MES: { L: '建钢-MES', K: 'STEEL_MES' },
  STEEL_MES_PLAN: { L: '建钢-计划表单', K: 'STEEL_MES_PLAN' },
  STEEL_MES_BUSINESS_VALUATION: { L: '建钢-商务计价表单', K: 'STEEL_MES_BUSINESS_VALUATION' },
  STEEL_MES_BUSINESS_STATISTICS: { L: '建钢-商务统计表单', K: 'STEEL_MES_BUSINESS_STATISTICS' },
  STEEL_MES_TASK: { L: '建钢-任务表单', K: 'STEEL_MES_TASK' },
  STEEL_MES_PRODUCTION: { L: '建钢-生产表单', K: 'STEEL_MES_PRODUCTION' },
  STEEL_MES_WAREHOUSE: { L: '建钢-出入库表单', K: 'STEEL_MES_WAREHOUSE' },
  STEEL_MES_SUMMARY: { L: '建钢-汇总表单', K: 'STEEL_MES_SUMMARY' },
  STEEL_MES_WAGE: { L: '建钢-工资表单', K: 'STEEL_MES_WAGE' },
  STEEL_MES_REPORT: { L: '建钢-报表表单', K: 'STEEL_MES_REPORT' },
  // STEEL_MES_LOGISTICS_SUMMARY: { L: '建钢-物流表单', K: 'STEEL_MES_LOGISTICS_SUMMARY' },
  // BRIDGE_MES: { L: '桥梁-MES', K: 'BRIDGE_MES' },
  BRIDGE_MES_PLAN: { L: '桥梁-计划表单', K: 'BRIDGE_MES_PLAN' },
  BRIDGE_MES_BUSINESS_VALUATION: { L: '桥梁-商务计价表单', K: 'BRIDGE_MES_BUSINESS_VALUATION' },
  BRIDGE_LOGISTICS: { L: '桥梁-物流表单', K: 'BRIDGE_LOGISTICS' },
  BRIDGE_MES_TASK: { L: '桥梁-任务表单', K: 'BRIDGE_MES_TASK' },
  BRIDGE_MES_PRODUCTION: { L: '桥梁-生产表单', K: 'BRIDGE_MES_PRODUCTION' },
  BRIDGE_MES_WAREHOUSE: { L: '桥梁-出入库表单', K: 'BRIDGE_MES_WAREHOUSE' },
  BRIDGE_MES_SUMMARY: { L: '桥梁-汇总表单', K: 'BRIDGE_MES_SUMMARY' },
  BRIDGE_MES_WAGE: { L: '桥梁-工资表单', K: 'BRIDGE_MES_WAGE' },
  // WMS: { L: 'WMS系统', K: 'WMS' },
  WMS_WAREHOUSE: { L: 'WMS-出入库表单', K: 'WMS_WAREHOUSE' },
  WMS_PREPARES: { L: 'WMS-采购备料表单', K: 'WMS_PREPARES' },
  WMS_PREPARES_TRACK: { L: 'WMS-备料跟踪表单', K: 'WMS_PREPARES_TRACK' }

}
constantize(moduleTypeEnum)

// 表格类型
const tableTypeEnum = { // 如果一个表格属于两个模块，T: []
  CONTRACT_LEDGER: { L: '合同台账登记表', K: 'CONTRACT_LEDGER', T: moduleTypeEnum.CONTRACT.K },
  PROJECT_COLLECTION_SUMMARY: { L: '项目收款开票汇总表', K: 'PROJECT_COLLECTION_SUMMARY', T: moduleTypeEnum.CONTRACT.K },
  PROJECT_COLLECTION_DETAIL: { L: '项目收款明细表', K: 'PROJECT_COLLECTION_DETAIL', T: moduleTypeEnum.CONTRACT.K },
  PROJECT_COLLECTION_TYPE_DETAIL: { L: '项目收款分类明细表', K: 'PROJECT_COLLECTION_TYPE_DETAIL', T: moduleTypeEnum.CONTRACT.K },
  PROJECT_INVOICE_DETAIL: { L: '项目开票明细表', K: 'PROJECT_INVOICE_DETAIL', T: moduleTypeEnum.CONTRACT.K },
  PROJECT_ARREARS_WARNING: { L: '项目欠款预警表', K: 'PROJECT_ARREARS_WARNING', T: moduleTypeEnum.CONTRACT.K },
  COMPANY_COLLECTION_PLAN: { L: '月度收款计划表', K: 'COMPANY_COLLECTION_PLAN', T: moduleTypeEnum.CONTRACT.K },
  COMPANY_COLLECTION_PLAN_EXECUTION: { L: '月度收款计划执行表', K: 'COMPANY_COLLECTION_PLAN_EXECUTION', T: moduleTypeEnum.CONTRACT.K },
  PROJECT_REIMBURSEMENT: { L: '项目报销记录表', K: 'PROJECT_REIMBURSEMENT', T: moduleTypeEnum.CONTRACT.K },
  SHIP_INFO: { L: '发运信息', K: 'SHIP_INFO', T: moduleTypeEnum.CONTRACT.K },
  PROJECT_EXECUTION_LEDGER: { L: '项目合同台账', K: 'PROJECT_EXECUTION_LEDGER', T: moduleTypeEnum.CONTRACT.K },

  // 项目弹窗表格
  PROJECT_MATERIAL_COSTS_DETAIL: { L: '材料成本', K: 'PROJECT_MATERIAL_COSTS_DETAIL', T: moduleTypeEnum.CONTRACT.K },

  PROJECT_DELIVER_AMOUNT: { L: '项目发货额', K: 'PROJECT_DELIVER_AMOUNT', T: moduleTypeEnum.CONT_CENTER.K },
  PROJECT_MANAGEMENT_FEE: { L: '项目管理费', K: 'PROJECT_MANAGEMENT_FEE', T: moduleTypeEnum.CONT_CENTER.K },
  PROJECT_MATERIAL_CONT: { L: '项目材料成本', K: 'PROJECT_MATERIAL_CONT', T: moduleTypeEnum.CONT_CENTER.K },
  PROJECT_PRODUCTION_CONT: { L: '项目人工成本', K: 'PROJECT_PRODUCTION_CONT', T: moduleTypeEnum.CONT_CENTER.K },

  SUPPLIER_PAYMENT_DETAIL: { L: '供应商付款明细表', K: 'SUPPLIER_PAYMENT_DETAIL', T: moduleTypeEnum.SUPPLIER.K },
  SUPPLIER_INVOICE_DETAIL: { L: '供应商开票明细表', K: 'SUPPLIER_INVOICE_DETAIL', T: moduleTypeEnum.SUPPLIER.K },
  SUPPLIER_STATEMENT: { L: '供应商对账单', K: 'SUPPLIER_STATEMENT', T: moduleTypeEnum.SUPPLIER.K },
  MATERIAL_PAYMENT_AND_INVOICE: { L: '物料供应商付款及开票', K: 'MATERIAL_PAYMENT_AND_INVOICE', T: moduleTypeEnum.SUPPLIER.K },

  BRIDGE_MES_AREA: { L: '区域制定', K: 'BRIDGE_MES_AREA', T: moduleTypeEnum.BRIDGE_MES_PLAN.K },
  BRIDGE_MES_AREA_PLAN: { L: '计划制定', K: 'BRIDGE_MES_AREA_PLAN', T: moduleTypeEnum.BRIDGE_MES_PLAN.K },

  BRIDGE_MES_BUSINESS_ENTRY_BOX: { L: '箱体计价表', K: 'BRIDGE_MES_BUSINESS_ENTRY_BOX', T: moduleTypeEnum.BRIDGE_MES_BUSINESS_VALUATION.K },
  BRIDGE_MES_BUSINESS_ENTRY_SINGLE_ELEMENT: { L: '单元件计价表', K: 'BRIDGE_MES_BUSINESS_ENTRY_SINGLE_ELEMENT', T: moduleTypeEnum.BRIDGE_MES_BUSINESS_VALUATION.K },
  BRIDGE_MES_BUSINESS_ENTRY_AUXILIARY_MATERIAL: { L: '辅材计价表', K: 'BRIDGE_MES_BUSINESS_ENTRY_AUXILIARY_MATERIAL', T: moduleTypeEnum.BRIDGE_MES_BUSINESS_VALUATION.K },
  BRIDGE_MES_BUSINESS_OUTBOUND_PROJECT: { L: '出库表(汇总)', K: 'BRIDGE_MES_BUSINESS_OUTBOUND_PROJECT', T: moduleTypeEnum.BRIDGE_MES_BUSINESS_VALUATION.K },
  BRIDGE_MES_BUSINESS_OUTBOUND_MONOMER: { L: '出库表(单体)', K: 'BRIDGE_MES_BUSINESS_OUTBOUND_MONOMER', T: moduleTypeEnum.BRIDGE_MES_BUSINESS_VALUATION.K },
  BRIDGE_MES_BUSINESS_INSTALLATION_PROJECT: { L: '安装表(汇总)', K: 'BRIDGE_MES_BUSINESS_INSTALLATION_PROJECT', T: moduleTypeEnum.BRIDGE_MES_BUSINESS_VALUATION.K },
  BRIDGE_MES_BUSINESS_INSTALLATION_MONOMER: { L: '安装表(单体)', K: 'BRIDGE_MES_BUSINESS_INSTALLATION_MONOMER', T: moduleTypeEnum.BRIDGE_MES_BUSINESS_VALUATION.K },
  BRIDGE_MES_BUSINESS_INSTALLATION_AUXILIARY_MATERIAL: { L: '辅材安装表', K: 'BRIDGE_MES_BUSINESS_INSTALLATION_AUXILIARY_MATERIAL', T: moduleTypeEnum.BRIDGE_MES_BUSINESS_VALUATION.K },
  BRIDGE_MES_BUSINESS_TRIP_TRACKING: { L: '单次发货统计表', K: 'BRIDGE_MES_BUSINESS_TRIP_TRACKING', T: moduleTypeEnum.BRIDGE_MES_BUSINESS_VALUATION.K },

  BRIDGE_MES_PACK: { L: '桥梁-打包清单', K: 'BRIDGE_MES_PACK', T: moduleTypeEnum.BRIDGE_LOGISTICS.K },
  BRIDGE_MES_PACK_SHIP: { L: '桥梁-发运汇总表', K: 'BRIDGE_MES_PACK_SHIP', T: moduleTypeEnum.BRIDGE_LOGISTICS.K },
  BRIDGE_MES_PACK_SHIP_DETAIL: { L: '桥梁-发运详情', K: 'BRIDGE_MES_PACK_SHIP_DETAIL', T: moduleTypeEnum.BRIDGE_LOGISTICS.K },
  BRIDGE_MES_PACK_RECEIPT: { L: '桥梁-收货状态汇总表', K: 'BRIDGE_MES_PACK_RECEIPT', T: moduleTypeEnum.BRIDGE_LOGISTICS.K },
  BRIDGE_MES_PACK_SHIPMENT_DETAIL: { L: '桥梁-发货清单', K: 'BRIDGE_MES_PACK_SHIPMENT_DETAIL', T: moduleTypeEnum.BRIDGE_LOGISTICS.K },
  BRIDGE_MES_LOGISTICS_SUMMARY: { L: '桥梁-物流汇总表', K: 'BRIDGE_MES_LOGISTICS_SUMMARY', T: moduleTypeEnum.BRIDGE_LOGISTICS.K },

  BRIDGE_MES_TASK_BOX: { L: '箱体任务清单', K: 'BRIDGE_MES_TASK_BOX', T: moduleTypeEnum.BRIDGE_MES_TASK.K },
  BRIDGE_MES_TASK_MACHINE_PART: { L: '零件任务清单', K: 'BRIDGE_MES_TASK_MACHINE_PART', T: moduleTypeEnum.BRIDGE_MES_TASK.K },
  BRIDGE_MES_TASK_SINGLE_ELEMENT: { L: '单元件任务清单', K: 'BRIDGE_MES_TASK_SINGLE_ELEMENT', T: moduleTypeEnum.BRIDGE_MES_TASK.K },
  BRIDGE_MES_PRODUCTION_STATE_BOX: { L: '箱体工序任务表', K: 'BRIDGE_MES_PRODUCTION_STATE_BOX', T: moduleTypeEnum.BRIDGE_MES_TASK.K },
  BRIDGE_MES_PRODUCTION_STATE_SINGLE_ELEMENT: { L: '单元件工序任务表', K: 'BRIDGE_MES_PRODUCTION_STATE_SINGLE_ELEMENT', T: moduleTypeEnum.BRIDGE_MES_TASK.K },
  BRIDGE_MES_PRODUCTION_STATE_MACHINE_PART: { L: '零件工序任务表', K: 'BRIDGE_MES_PRODUCTION_STATE_MACHINE_PART', T: moduleTypeEnum.BRIDGE_MES_TASK.K },

  BRIDGE_MES_COMPLEX_STATE_BOX: { L: '箱体汇总统计表', K: 'BRIDGE_MES_COMPLEX_STATE_BOX', T: moduleTypeEnum.BRIDGE_MES_SUMMARY.K },
  BRIDGE_MES_COMPLEX_STATE_SINGLE_ELEMENT: { L: '单元件汇总统计表', K: 'BRIDGE_MES_COMPLEX_STATE_SINGLE_ELEMENT', T: moduleTypeEnum.BRIDGE_MES_SUMMARY.K },
  BRIDGE_MES_COMPLEX_STATE_AUXILIARY_MATERIAL: { L: '辅材汇总统计表', K: 'BRIDGE_MES_COMPLEX_STATE_AUXILIARY_MATERIAL', T: moduleTypeEnum.BRIDGE_MES_SUMMARY.K },

  BRIDGE_MES_REPORT_PROJECT_PRODUCTION: { L: '生产表(项目)', K: 'BRIDGE_MES_REPORT_PROJECT_PRODUCTION', T: moduleTypeEnum.BRIDGE_MES_PRODUCTION.K },
  BRIDGE_MES_REPORT_FACTORY_PRODUCTION: { L: '生产表(工厂)', K: 'BRIDGE_MES_REPORT_FACTORY_PRODUCTION', T: moduleTypeEnum.BRIDGE_MES_PRODUCTION.K },
  BRIDGE_MES_REPORT_TEAM_OUTPUT_BOX: { L: '箱体产量表(班组)', K: 'BRIDGE_MES_REPORT_TEAM_OUTPUT_BOX', T: moduleTypeEnum.BRIDGE_MES_PRODUCTION.K },
  BRIDGE_MES_REPORT_TEAM_OUTPUT_MACHINE_PART: { L: '零件产量表(班组)', K: 'BRIDGE_MES_REPORT_TEAM_OUTPUT_MACHINE_PART', T: moduleTypeEnum.BRIDGE_MES_PRODUCTION.K },
  BRIDGE_MES_REPORT_TEAM_OUTPUT_SINGLE_ELEMENT: { L: '单元件产量表(班组)', K: 'BRIDGE_MES_REPORT_TEAM_OUTPUT_SINGLE_ELEMENT', T: moduleTypeEnum.BRIDGE_MES_PRODUCTION.K },

  BRIDGE_MES_REPORT_OUTBOUND: { L: '出库表(全部项目)', K: 'BRIDGE_MES_REPORT_OUTBOUND', T: moduleTypeEnum.BRIDGE_MES_WAREHOUSE.K },
  BRIDGE_MES_REPORT_OUTBOUND_PROJECT: { L: '出库表(项目)', K: 'BRIDGE_MES_REPORT_OUTBOUND_PROJECT', T: moduleTypeEnum.BRIDGE_MES_WAREHOUSE.K },
  BRIDGE_MES_REPORT_OUTBOUND_AUXILIARY_MATERIAL: { L: '辅材出库表(全部项目)', K: 'BRIDGE_MES_REPORT_OUTBOUND_AUXILIARY_MATERIAL', T: moduleTypeEnum.BRIDGE_MES_WAREHOUSE.K },
  BRIDGE_MES_REPORT_OUTBOUND_PROJECT_AUXILIARY_MATERIAL: { L: '辅材出库表(项目)', K: 'BRIDGE_MES_REPORT_OUTBOUND_PROJECT_AUXILIARY_MATERIAL', T: moduleTypeEnum.BRIDGE_MES_WAREHOUSE.K },
  BRIDGE_MES_REPORT_INSTALLATION: { L: '安装表(项目)', K: 'BRIDGE_MES_REPORT_INSTALLATION', T: moduleTypeEnum.BRIDGE_MES_WAREHOUSE.K },

  BRIDGE_MES_WAREHOUSE_STATE_BOX: { L: '箱体出入库统计表', K: 'BRIDGE_MES_WAREHOUSE_STATE_BOX', T: moduleTypeEnum.BRIDGE_MES_WAREHOUSE.K },
  BRIDGE_MES_WAREHOUSE_STATE_SINGLE_ELEMENT: { L: '单元件出入库统计表', K: 'BRIDGE_MES_WAREHOUSE_STATE_SINGLE_ELEMENT', T: moduleTypeEnum.BRIDGE_MES_WAREHOUSE.K },
  BRIDGE_MES_WAREHOUSE_STATE_AUXILIARY_MATERIAL: { L: '辅材出入库统计表', K: 'BRIDGE_MES_WAREHOUSE_STATE_AUXILIARY_MATERIAL', T: moduleTypeEnum.BRIDGE_MES_WAREHOUSE.K },
  BRIDGE_MES_SITE_WAREHOUSE_STATE_BOX: { L: '箱体收安统计表', K: 'BRIDGE_MES_SITE_WAREHOUSE_STATE_BOX', T: moduleTypeEnum.BRIDGE_MES_WAREHOUSE.K },
  BRIDGE_MES_SITE_WAREHOUSE_STATE_SINGLE_ELEMENT: { L: '单元件收安统计表', K: 'BRIDGE_MES_SITE_WAREHOUSE_STATE_SINGLE_ELEMENT', T: moduleTypeEnum.BRIDGE_MES_WAREHOUSE.K },
  BRIDGE_MES_SITE_WAREHOUSE_STATE_AUXILIARY_MATERIAL: { L: '辅材收安统计表', K: 'BRIDGE_MES_SITE_WAREHOUSE_STATE_AUXILIARY_MATERIAL', T: moduleTypeEnum.BRIDGE_MES_WAREHOUSE.K },

  BRIDGE_MES_REPORT_TEAM_PIECE_WAGE: { L: '班组计件工资表', K: 'BRIDGE_MES_REPORT_TEAM_PIECE_WAGE', T: moduleTypeEnum.BRIDGE_MES_WAGE.K },
  BRIDGE_MES_REPORT_OUTPUT_WAGE: { L: '产量工资表', K: 'BRIDGE_MES_REPORT_OUTPUT_WAGE', T: moduleTypeEnum.BRIDGE_MES_WAGE.K },

  STEEL_MES_AREA: { L: '区域制定', K: 'STEEL_MES_AREA', T: moduleTypeEnum.STEEL_MES_PLAN.K },
  STEEL_MES_AREA_PLAN: { L: '计划制定', K: 'STEEL_MES_AREA_PLAN', T: moduleTypeEnum.STEEL_MES_PLAN.K },

  STEEL_MES_BUSINESS_ENTRY_STRUCTURE: { L: '结构计价表', K: 'STEEL_MES_BUSINESS_ENTRY_STRUCTURE', T: moduleTypeEnum.STEEL_MES_BUSINESS_VALUATION.K },
  STEEL_MES_BUSINESS_ENTRY_ENCLOSURE: { L: '围护计价表', K: 'STEEL_MES_BUSINESS_ENTRY_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_BUSINESS_VALUATION.K },
  STEEL_MES_BUSINESS_ENTRY_AUXILIARY_MATERIAL: { L: '辅材计价表', K: 'STEEL_MES_BUSINESS_ENTRY_AUXILIARY_MATERIAL', T: moduleTypeEnum.STEEL_MES_BUSINESS_VALUATION.K },
  STEEL_MES_BUSINESS_OUTBOUND_PROJECT: { L: '出库表(汇总)', K: 'STEEL_MES_BUSINESS_OUTBOUND_PROJECT', T: moduleTypeEnum.STEEL_MES_BUSINESS_STATISTICS.K },
  STEEL_MES_BUSINESS_OUTBOUND_MONOMER: { L: '出库表(单体)', K: 'STEEL_MES_BUSINESS_OUTBOUND_MONOMER', T: moduleTypeEnum.STEEL_MES_BUSINESS_STATISTICS.K },
  STEEL_MES_BUSINESS_INSTALLATION_PROJECT: { L: '安装表(汇总)', K: 'STEEL_MES_BUSINESS_INSTALLATION_PROJECT', T: moduleTypeEnum.STEEL_MES_BUSINESS_STATISTICS.K },
  STEEL_MES_BUSINESS_INSTALLATION_MONOMER: { L: '安装表(单体)', K: 'STEEL_MES_BUSINESS_INSTALLATION_MONOMER', T: moduleTypeEnum.STEEL_MES_BUSINESS_STATISTICS.K },
  STEEL_MES_BUSINESS_TRIP_TRACKING: { L: '单次发货统计表', K: 'STEEL_MES_BUSINESS_TRIP_TRACKING', T: moduleTypeEnum.STEEL_MES_BUSINESS_STATISTICS.K },

  STEEL_MES_PACK: { L: '建钢-打包清单', K: 'STEEL_MES_PACK', T: moduleTypeEnum.MES_LOGISTICS.K },
  STEEL_MES_PACK_SHIP: { L: '建钢-发运汇总表', K: 'STEEL_MES_PACK_SHIP', T: moduleTypeEnum.MES_LOGISTICS.K },
  STEEL_MES_PACK_SHIP_DETAIL: { L: '建钢-发运详情', K: 'STEEL_MES_PACK_SHIP_DETAIL', T: moduleTypeEnum.MES_LOGISTICS.K },
  STEEL_MES_PACK_RECEIPT: { L: '建钢-收货状态汇总表', K: 'STEEL_MES_PACK_RECEIPT', T: moduleTypeEnum.MES_LOGISTICS.K },
  STEEL_MES_PACK_SHIPMENT_DETAIL: { L: '建钢-发货清单', K: 'STEEL_MES_PACK_SHIPMENT_DETAIL', T: moduleTypeEnum.MES_LOGISTICS.K },
  MES_LOGISTICS_SUMMARY: { L: 'MES-物流汇总表', K: 'MES_LOGISTICS_SUMMARY', T: moduleTypeEnum.MES_LOGISTICS.K },
  MES_LOGISTICS_ORDER_DELIVERY_DETAIL: { L: 'MES-制成品物流订单发运详情', K: 'MES_LOGISTICS_ORDER_DELIVERY_DETAIL', T: moduleTypeEnum.MES_LOGISTICS.K },

  STEEL_MES_TASK_STRUCTURE: { L: '结构任务清单', K: 'STEEL_MES_TASK_STRUCTURE', T: moduleTypeEnum.STEEL_MES_TASK.K },
  STEEL_MES_TASK_MACHINE_PART: { L: '零件任务清单', K: 'STEEL_MES_TASK_MACHINE_PART', T: moduleTypeEnum.STEEL_MES_TASK.K },
  STEEL_MES_TASK_ENCLOSURE: { L: '围护任务清单', K: 'STEEL_MES_TASK_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_TASK.K },
  STEEL_MES_PRODUCTION_STATE_STRUCTURE: { L: '结构工序任务表', K: 'STEEL_MES_PRODUCTION_STATE_STRUCTURE', T: moduleTypeEnum.STEEL_MES_TASK.K },
  STEEL_MES_PRODUCTION_STATE_ENCLOSURE: { L: '围护工序任务表', K: 'STEEL_MES_PRODUCTION_STATE_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_TASK.K },
  STEEL_MES_PRODUCTION_STATE_MACHINE_PART: { L: '零件工序任务表', K: 'STEEL_MES_PRODUCTION_STATE_MACHINE_PART', T: moduleTypeEnum.STEEL_MES_TASK.K },

  STEEL_MES_COMPLEX_STATE_STRUCTURE: { L: '结构汇总统计表', K: 'STEEL_MES_COMPLEX_STATE_STRUCTURE', T: moduleTypeEnum.STEEL_MES_SUMMARY.K },
  STEEL_MES_COMPLEX_STATE_ENCLOSURE: { L: '围护汇总统计表', K: 'STEEL_MES_COMPLEX_STATE_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_SUMMARY.K },
  STEEL_MES_COMPLEX_STATE_AUXILIARY_MATERIAL: { L: '辅材汇总统计表', K: 'STEEL_MES_COMPLEX_STATE_AUXILIARY_MATERIAL', T: moduleTypeEnum.STEEL_MES_SUMMARY.K },

  STEEL_MES_REPORT_PROJECT_PRODUCTION_STRUCTURE: { L: '结构生产表(项目)', K: 'STEEL_MES_REPORT_PROJECT_PRODUCTION_STRUCTURE', T: moduleTypeEnum.STEEL_MES_PRODUCTION.K },
  STEEL_MES_REPORT_FACTORY_PRODUCTION_STRUCTURE: { L: '结构生产表(工厂)', K: 'STEEL_MES_REPORT_FACTORY_PRODUCTION_STRUCTURE', T: moduleTypeEnum.STEEL_MES_PRODUCTION.K },
  STEEL_MES_REPORT_PROJECT_PRODUCTION_ENCLOSURE: { L: '围护生产表(项目)', K: 'STEEL_MES_REPORT_PROJECT_PRODUCTION_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_PRODUCTION.K },
  STEEL_MES_REPORT_FACTORY_PRODUCTION_ENCLOSURE: { L: '围护生产表(工厂)', K: 'STEEL_MES_REPORT_FACTORY_PRODUCTION_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_PRODUCTION.K },
  STEEL_MES_REPORT_TEAM_OUTPUT_STRUCTURE: { L: '构件产量表(班组)', K: 'STEEL_MES_REPORT_TEAM_OUTPUT_STRUCTURE', T: moduleTypeEnum.STEEL_MES_PRODUCTION.K },
  STEEL_MES_REPORT_TEAM_OUTPUT_MACHINE_PART: { L: '零件产量表(班组)', K: 'STEEL_MES_REPORT_TEAM_OUTPUT_MACHINE_PART', T: moduleTypeEnum.STEEL_MES_PRODUCTION.K },
  STEEL_MES_REPORT_TEAM_OUTPUT_ENCLOSURE: { L: '围护产量表(班组)', K: 'STEEL_MES_REPORT_TEAM_OUTPUT_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_PRODUCTION.K },

  STEEL_MES_REPORT_OUTBOUND_STRUCTURE: { L: '结构出库表(全部项目)', K: 'STEEL_MES_REPORT_OUTBOUND_STRUCTURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_REPORT_OUTBOUND_PROJECT_STRUCTURE: { L: '结构出库表(项目)', K: 'STEEL_MES_REPORT_OUTBOUND_PROJECT_STRUCTURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_REPORT_OUTBOUND_ENCLOSURE: { L: '围护出库表(全部项目)', K: 'STEEL_MES_REPORT_OUTBOUND_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_REPORT_OUTBOUND_PROJECT_ENCLOSURE: { L: '围护出库表(项目)', K: 'STEEL_MES_REPORT_OUTBOUND_PROJECT_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_REPORT_OUTBOUND_AUXILIARY_MATERIAL: { L: '辅材出库表(全部项目)', K: 'STEEL_MES_REPORT_OUTBOUND_AUXILIARY_MATERIAL', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_REPORT_OUTBOUND_PROJECT_AUXILIARY_MATERIAL: { L: '辅材出库表(项目)', K: 'STEEL_MES_REPORT_OUTBOUND_PROJECT_AUXILIARY_MATERIAL', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_REPORT_INSTALLATION_STRUCTURE: { L: '结构安装表(项目)', K: 'STEEL_MES_REPORT_INSTALLATION_STRUCTURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_REPORT_INSTALLATION_ENCLOSURE: { L: '围护安装表(项目)', K: 'STEEL_MES_REPORT_INSTALLATION_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },

  STEEL_MES_WAREHOUSE_STATE_STRUCTURE: { L: '结构出入库统计表', K: 'STEEL_MES_WAREHOUSE_STATE_STRUCTURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_WAREHOUSE_STATE_ENCLOSURE: { L: '围护出入库统计表', K: 'STEEL_MES_WAREHOUSE_STATE_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_WAREHOUSE_STATE_AUXILIARY_MATERIAL: { L: '辅材出入库统计表', K: 'STEEL_MES_WAREHOUSE_STATE_AUXILIARY_MATERIAL', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_WAREHOUSE_STATE_REPORT: { L: '入发存报表', K: 'STEEL_MES_WAREHOUSE_STATE_REPORT', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_WAREHOUSE_STATE_REPORT_PRODUCT_ENCLOSURE: { L: '入发存项目明细报表-围护', K: 'STEEL_MES_WAREHOUSE_STATE_REPORT_PRODUCT_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_WAREHOUSE_STATE_REPORT_PRODUCT_STRUCTURE: { L: '入发存项目明细报表-结构', K: 'STEEL_MES_WAREHOUSE_STATE_REPORT_PRODUCT_STRUCTURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_WAREHOUSE_STATE_REPORT_SUMMARY_ENCLOSURE: { L: '入发存汇总明细报表-围护', K: 'STEEL_MES_WAREHOUSE_STATE_REPORT_SUMMARY_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_WAREHOUSE_STATE_REPORT_SUMMARY_STRUCTURE: { L: '入发存汇总明细报表-结构', K: 'STEEL_MES_WAREHOUSE_STATE_REPORT_SUMMARY_STRUCTURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_SITE_WAREHOUSE_STATE_STRUCTURE: { L: '结构收安统计表', K: 'STEEL_MES_SITE_WAREHOUSE_STATE_STRUCTURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_SITE_WAREHOUSE_STATE_ENCLOSURE: { L: '围护收安统计表', K: 'STEEL_MES_SITE_WAREHOUSE_STATE_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },
  STEEL_MES_SITE_WAREHOUSE_STATE_AUXILIARY_MATERIAL: { L: '辅材收安统计表', K: 'STEEL_MES_SITE_WAREHOUSE_STATE_AUXILIARY_MATERIAL', T: moduleTypeEnum.STEEL_MES_WAREHOUSE.K },

  STEEL_MES_REPORT_TEAM_PIECE_WAGE_STRUCTURE: { L: '构件班组计件工资表', K: 'STEEL_MES_REPORT_TEAM_PIECE_WAGE_STRUCTURE', T: moduleTypeEnum.STEEL_MES_WAGE.K },
  STEEL_MES_REPORT_TEAM_PIECE_WAGE_ENCLOSURE: { L: '围护班组计件工资表', K: 'STEEL_MES_REPORT_TEAM_PIECE_WAGE_ENCLOSURE', T: moduleTypeEnum.STEEL_MES_WAGE.K },
  STEEL_MES_REPORT_OUTPUT_WAGE: { L: '产量工资表', K: 'STEEL_MES_REPORT_OUTPUT_WAGE', T: moduleTypeEnum.STEEL_MES_WAGE.K },

  STEEL_MES_REPORT_STEEL_DOSAGE: { L: '钢材使用用量对比', K: 'STEEL_MES_REPORT_STEEL_DOSAGE', T: moduleTypeEnum.STEEL_MES_REPORT.K },

  WMS_IN_WAREHOUSE_VOUCHER: { L: '入库单', K: 'WMS_IN_WAREHOUSE_VOUCHER', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_OUT_WAREHOUSE_VOUCHER: { L: '出库（领料）单', K: 'WMS_OUT_WAREHOUSE_VOUCHER', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_OUT_WAREHOUSE_RECORD_SUMMARY: { L: '出库汇总单', K: 'WMS_OUT_WAREHOUSE_RECORD_SUMMARY', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_RETURN_WAREHOUSE_VOUCHER: { L: '还库单', K: 'WMS_RETURN_WAREHOUSE_VOUCHER', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_QUIT_WAREHOUSE_VOUCHER: { L: '退库单', K: 'WMS_QUIT_WAREHOUSE_VOUCHER', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_MATERIAL_MOVE_HOUSE_VOUCHER: { L: '物料调拨单', K: 'WMS_MATERIAL_MOVE_HOUSE_VOUCHER', T: moduleTypeEnum.WMS_WAREHOUSE.K },

  WMS_IN_RECORD_SUMMARY_DETAIL: { L: '入库汇总明细表', K: 'WMS_IN_RECORD_SUMMARY_DETAIL', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_OUT_RECORD_SUMMARY_DETAIL: { L: '出库汇总明细表', K: 'WMS_OUT_RECORD_SUMMARY_DETAIL', T: moduleTypeEnum.WMS_WAREHOUSE.K },

  WMS_REPORT_IN_SUMMARY: { L: '物料入库一览表', K: 'WMS_REPORT_IN_SUMMARY', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_REPORT_OUT_SUMMARY: { L: '物料出库一览表', K: 'WMS_REPORT_OUT_SUMMARY', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_REPORT_INVENTORY_SUMMARY: { L: '物料仓库存一览表', K: 'WMS_REPORT_INVENTORY_SUMMARY', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_INVENTORY_MANAGE_SUMMARY: { L: '物料盘存汇总表', K: 'WMS_INVENTORY_MANAGE_SUMMARY', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_INVENTORY_MANAGE_END_SUMMARY_DETAIL: { L: '物料盘存期末汇总明细表', K: 'WMS_INVENTORY_MANAGE_END_SUMMARY_DETAIL', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_INVENTORY_MANAGE_INBOUND_SUMMARY_DETAIL: { L: '物料盘存入库汇总明细表', K: 'WMS_INVENTORY_MANAGE_INBOUND_SUMMARY_DETAIL', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_INVENTORY_MANAGE_OUTBOUND_SUMMARY_DETAIL: { L: '物料盘存出库汇总明细表', K: 'WMS_INVENTORY_MANAGE_OUTBOUND_SUMMARY_DETAIL', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_INVENTORY_MANAGE_BEGIN_SUMMARY: { L: '期初库存汇总表', K: 'WMS_INVENTORY_MANAGE_BEGIN_SUMMARY', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_INVENTORY_MANAGE_BEGIN_GM_SUMMARY: { L: '期初库存汇总表-辅材', K: 'WMS_INVENTORY_MANAGE_BEGIN_GM_SUMMARY', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_INVENTORY_MANAGE_IN_SUMMARY: { L: '原材料入库汇总表', K: 'WMS_INVENTORY_MANAGE_IN_SUMMARY', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_INVENTORY_MANAGE_OUT_SUMMARY: { L: '原材料出库汇总表', K: 'WMS_INVENTORY_MANAGE_OUT_SUMMARY', T: moduleTypeEnum.WMS_WAREHOUSE.K },
  WMS_INVENTORY_MANAGE_END_SUMMARY: { L: '期末库存汇总表', K: 'WMS_INVENTORY_MANAGE_END_SUMMARY', T: moduleTypeEnum.WMS_WAREHOUSE.K },

  WMS_PREPARES_CUSTOM_SUMMARY: { L: '物料备料汇总单', K: 'WMS_PREPARES_CUSTOM_SUMMARY', T: moduleTypeEnum.WMS_PREPARES.K },
  WMS_PREPARES_CUSTOM_STEEL_PLATE: { L: '钢板采购清单', K: 'WMS_PREPARES_CUSTOM_STEEL_PLATE', T: moduleTypeEnum.WMS_PREPARES.K },
  WMS_PREPARES_CUSTOM_SECTION_STEEL: { L: '型材采购清单', K: 'WMS_PREPARES_CUSTOM_SECTION_STEEL', T: moduleTypeEnum.WMS_PREPARES.K },
  WMS_PREPARES_CUSTOM_STEEL_COIL: { L: '钢卷采购清单', K: 'WMS_PREPARES_CUSTOM_STEEL_COIL', T: moduleTypeEnum.WMS_PREPARES.K },
  WMS_PREPARES_CUSTOM_ENCLOSURE: { L: '成品围护采购清单', K: 'WMS_PREPARES_CUSTOM_ENCLOSURE', T: moduleTypeEnum.WMS_PREPARES.K },
  WMS_PREPARES_CUSTOM_MATERIAL: { L: '辅材采购清单', K: 'WMS_PREPARES_CUSTOM_MATERIAL', T: moduleTypeEnum.WMS_PREPARES.K },

  WMS_PREPARES_TRACK_STEEL_PLATE: { L: '钢板备料跟踪单', K: 'WMS_PREPARES_TRACK_STEEL_PLATE', T: moduleTypeEnum.WMS_PREPARES_TRACK.K },
  WMS_PREPARES_TRACK_SECTION_STEEL: { L: '型材备料跟踪单', K: 'WMS_PREPARES_TRACK_SECTION_STEEL', T: moduleTypeEnum.WMS_PREPARES_TRACK.K },
  WMS_PREPARES_TRACK_STEEL_COIL: { L: '钢卷备料跟踪单', K: 'WMS_PREPARES_TRACK_STEEL_COIL', T: moduleTypeEnum.WMS_PREPARES_TRACK.K },
  WMS_PREPARES_TRACK_ENCLOSURE: { L: '成品围护备料跟踪单', K: 'WMS_PREPARES_TRACK_ENCLOSURE', T: moduleTypeEnum.WMS_PREPARES_TRACK.K },
  WMS_PREPARES_TRACK_MATERIAL: { L: '辅材备料跟踪单', K: 'WMS_PREPARES_TRACK_MATERIAL', T: moduleTypeEnum.WMS_PREPARES_TRACK.K },

  WMS_LOGISTICS_DELIVERY_METE: { L: '物流汇总单', K: 'WMS_LOGISTICS_DELIVERY_METE', T: moduleTypeEnum.WMS_LOGISTICS.K },
  WMS_LOGISTICS_ORDER_MATERIAL_DETAIL: { L: '订单收货详情', K: 'WMS_LOGISTICS_ORDER_MATERIAL_DETAIL', T: moduleTypeEnum.WMS_LOGISTICS.K }
}
constantize(tableTypeEnum)

// 一个模板对应多个接口，尽量一一对应，在特殊情况下需要做特殊处理
const apikey = {
  PROJECT_MAIN_MATERIAL_CONT: 'PROJECT_MATERIAL_CONT', // 项目主材出库成本
  PROJECT_MAIN_MATERIAL_RETURN_CONT: 'PROJECT_MATERIAL_RETURN_CONT', // 项目主材还库成本
  PROJECT_AUXILIARY_MAIN_MATERIAL_CONT: 'PROJECT_MATERIAL_CONT', // 项目辅材出库成本
  PROJECT_AUXILIARY_MAIN_MATERIAL_RETURN_CONT: 'PROJECT_MATERIAL_RETURN_CONT', // 项目辅材还库成本

  MATERIAL_SUPPLIER_PAYMENT_DETAIL: 'SUPPLIER_PAYMENT_DETAIL', // 物料供应商付款明细
  LOGISTICS_SUPPLIER_PAYMENT_DETAIL: 'SUPPLIER_PAYMENT_DETAIL', // 物流供应商付款明细
  MATERIAL_SUPPLIER_INVOICE_DETAIL: 'SUPPLIER_INVOICE_DETAIL', // 物流供应商开票明细
  LOGISTICS_SUPPLIER_INVOICE_DETAIL: 'SUPPLIER_INVOICE_DETAIL', // 物流供应商开票明细

  MATERIAL_SUPPLIER_STATEMENT: 'SUPPLIER_STATEMENT', // 物料供应商付款明细
  LOGISTICS_SUPPLIER_STATEMENT: 'SUPPLIER_STATEMENT', // 物流供应商付款明细

  BRIDGE_MES_BUSINESS_INSTALLATION_PROJECT_BOX: 'BRIDGE_MES_BUSINESS_INSTALLATION_PROJECT', // 桥梁商务项目安装表
  BRIDGE_MES_BUSINESS_INSTALLATION_PROJECT_SINGLE_ELEMENT: 'BRIDGE_MES_BUSINESS_INSTALLATION_PROJECT', // 桥梁商务项目安装表
  BRIDGE_MES_BUSINESS_INSTALLATION_MONOMER_BOX: 'BRIDGE_MES_BUSINESS_INSTALLATION_MONOMER', // 桥梁商务单体安装表
  BRIDGE_MES_BUSINESS_INSTALLATION_MONOMER_SINGLE_ELEMENT: 'BRIDGE_MES_BUSINESS_INSTALLATION_MONOMER', // 桥梁商务单体安装表

  STEEL_MES_LOGISTICS_SUMMARY: 'MES_LOGISTICS_SUMMARY' // 建钢物流汇总表
  // MES_LOGISTICS_BY_ORDER: 'MES_LOGISTICS_SUMMARY' // 订单物流信息
  // MES_LOGISTICS_SUMMARY
}
constantize(apikey)

export {
  moduleTypeEnum, // 模块类型
  tableTypeEnum, // 表格类型
  apikey
}

export default {
  key2val,
  toArr,
  getBits,
  setEnumValue
}
