
const getMenu = {
  url: '/api/menu',
  method: 'get',
  timeout: 1000,
  response: () => {
    return {
      'code': 20000,
      'message': '操作成功',
      'data': {
        'totalElements': 11,
        'content': [{
          'id': 3,
          'pid': 0,
          'category': 0,
          'type': 0,
          'name': '合同管理',
          'permission': '',
          'permissionTypeId': null,
          'icon': 'contract',
          'path': '',
          'redirect': 'contract',
          'component': '',
          'componentName': '',
          'iframe': false,
          'cache': false,
          'hidden': false,
          'sort': 1,
          'alwaysShow': false,
          'children': [{
            'id': 99,
            'pid': 3,
            'category': 0,
            'type': 1,
            'name': '项目管理',
            'permission': '',
            'permissionTypeId': null,
            'icon': 'contract2',
            'path': 'contract',
            'redirect': '/contract/project',
            'component': '',
            'componentName': 'ContractProjectManage',
            'iframe': false,
            'cache': false,
            'hidden': false,
            'sort': 1,
            'alwaysShow': false,
            'children': [{
              'id': 100,
              'pid': 99,
              'category': 0,
              'type': 1,
              'name': '项目列表',
              'permission': '',
              'permissionTypeId': null,
              'icon': 'contract2',
              'path': 'project',
              'redirect': '',
              'component': '/contract/project/index',
              'componentName': 'ContractProject',
              'iframe': false,
              'cache': false,
              'hidden': false,
              'sort': 1,
              'alwaysShow': false,
              'children': [{
                'id': 414,
                'pid': 100,
                'category': 0,
                'type': 2,
                'name': '合同详情',
                'permission': 'contract:detail',
                'permissionTypeId': 3,
                'icon': null,
                'path': null,
                'redirect': null,
                'component': null,
                'componentName': null,
                'iframe': false,
                'cache': false,
                'hidden': false,
                'sort': 1,
                'alwaysShow': false,
                'children': null
              }, {
                'id': 415,
                'pid': 100,
                'category': 0,
                'type': 2,
                'name': '合同立项',
                'permission': 'contract:add',
                'permissionTypeId': 2,
                'icon': null,
                'path': null,
                'redirect': null,
                'component': null,
                'componentName': null,
                'iframe': false,
                'cache': false,
                'hidden': false,
                'sort': 1,
                'alwaysShow': false,
                'children': null
              }, {
                'id': 416,
                'pid': 100,
                'category': 0,
                'type': 2,
                'name': '下载合同台账',
                'permission': 'contract:downloadContractLedger',
                'permissionTypeId': 1,
                'icon': null,
                'path': null,
                'redirect': null,
                'component': null,
                'componentName': null,
                'iframe': false,
                'cache': false,
                'hidden': false,
                'sort': 1,
                'alwaysShow': false,
                'children': null
              }, {
                'id': 417,
                'pid': 100,
                'category': 0,
                'type': 2,
                'name': '下载合同信息',
                'permission': 'contract:download',
                'permissionTypeId': 1,
                'icon': null,
                'path': null,
                'redirect': null,
                'component': null,
                'componentName': null,
                'iframe': false,
                'cache': false,
                'hidden': false,
                'sort': 1,
                'alwaysShow': false,
                'children': null
              }, {
                'id': 418,
                'pid': 100,
                'category': 0,
                'type': 2,
                'name': '项目列表',
                'permission': 'project:get',
                'permissionTypeId': 3,
                'icon': null,
                'path': null,
                'redirect': null,
                'component': null,
                'componentName': null,
                'iframe': false,
                'cache': false,
                'hidden': false,
                'sort': 1,
                'alwaysShow': false,
                'children': null
              }, {
                'id': 419,
                'pid': 100,
                'category': 0,
                'type': 2,
                'name': '删除项目',
                'permission': 'project:del',
                'permissionTypeId': 2,
                'icon': null,
                'path': null,
                'redirect': null,
                'component': null,
                'componentName': null,
                'iframe': false,
                'cache': false,
                'hidden': false,
                'sort': 1,
                'alwaysShow': false,
                'children': null
              }, {
                'id': 420,
                'pid': 100,
                'category': 0,
                'type': 2,
                'name': '编辑项目状态',
                'permission': 'project:editStatus',
                'permissionTypeId': 2,
                'icon': null,
                'path': null,
                'redirect': null,
                'component': null,
                'componentName': null,
                'iframe': false,
                'cache': false,
                'hidden': false,
                'sort': 1,
                'alwaysShow': false,
                'children': null
              }, {
                'id': 421,
                'pid': 100,
                'category': 0,
                'type': 2,
                'name': '编辑项目成员',
                'permission': 'project:editMembers',
                'permissionTypeId': 2,
                'icon': null,
                'path': null,
                'redirect': null,
                'component': null,
                'componentName': null,
                'iframe': false,
                'cache': false,
                'hidden': false,
                'sort': 1,
                'alwaysShow': false,
                'children': null
              }, {
                'id': 1058,
                'pid': 100,
                'category': 0,
                'type': 2,
                'name': '打印合同信息',
                'permission': 'contract:print',
                'permissionTypeId': 3,
                'icon': null,
                'path': null,
                'redirect': null,
                'component': null,
                'componentName': null,
                'iframe': false,
                'cache': false,
                'hidden': false,
                'sort': 1,
                'alwaysShow': false,
                'children': null
              }]
            }]
          }]
        }]
      }
    }
  }
}

const addMenu = {
  url: '/api/menu',
  method: 'post',
  timeout: 1000,
  response: () => {
    return {
      'code': 20000,
      'message': '操作成功',
      'data': 10
    }
  }
}

const editMenu = {
  url: '/api/menu',
  method: 'put',
  timeout: 1000,
  response: () => {
    return {
      'code': 20000,
      'message': '操作成功',
      'data': 10
    }
  }
}

const delMenu = {
  url: '/api/menu',
  method: 'delete',
  timeout: 1000,
  response: () => {
    return {
      'code': 20000,
      'message': '成功'
    }
  }
}
const getMenuTree = {
  url: '/api/menu/tree',
  method: 'get',
  timeout: 1000,
  response: () => {
    return {
      'code': 20000,
      'message': '操作成功',
      'data': [{
        'id': 3,
        'label': '合同管理',
        'own': null,
        'permissionTypeId': null,
        'type': 0,
        'children': [{
          'id': 99,
          'label': '项目管理',
          'own': null,
          'permissionTypeId': null,
          'type': 1,
          'children': [{
            'id': 100,
            'label': '项目列表',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 414,
              'label': '合同详情',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 415,
              'label': '合同立项',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 416,
              'label': '下载合同台账',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 417,
              'label': '下载合同信息',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 418,
              'label': '项目列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 419,
              'label': '删除项目',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 420,
              'label': '编辑项目状态',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 421,
              'label': '编辑项目成员',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1058,
              'label': '打印合同信息',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }]
          }]
        }, {
          'id': 101,
          'label': '合同信息',
          'own': null,
          'permissionTypeId': null,
          'type': 1,
          'children': [{
            'id': 102,
            'label': '基本信息',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 422,
              'label': '获取合同基本信息',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 423,
              'label': '修改合同基本信息',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 424,
              'label': '下载合同附件',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 103,
            'label': '商务信息',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 425,
              'label': '获取合同商务信息',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 426,
              'label': '修改合同商务信息',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 427,
              'label': '下载结算附件',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 408,
            'label': '客户信息',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 428,
              'label': '获取合同客户信息',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 429,
              'label': '修改合同客户信息',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }]
          }]
        }, {
          'id': 409,
          'label': '收款管理',
          'own': null,
          'permissionTypeId': null,
          'type': 1,
          'children': [{
            'id': 410,
            'label': '收款列表',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 430,
              'label': '项目收款列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 431,
              'label': '合同信息',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 432,
              'label': '发运信息',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1059,
              'label': '项目收款汇总表(下载)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1060,
              'label': '项目收款汇总表(打印)',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1173,
              'label': '结算',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1163,
              'label': '收款列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1164,
              'label': '收款添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1165,
              'label': '收款编辑',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1166,
              'label': '收款删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1167,
              'label': '收款明细(下载)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1175,
              'label': '收款明细(打印)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1168,
              'label': '开票列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1169,
              'label': '开票添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1170,
              'label': '开票编辑',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1171,
              'label': '开票删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1174,
              'label': '开票办理',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1172,
              'label': '开票明细(下载)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1176,
              'label': '开票明细(打印)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1360,
              'label': '收款审核',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 411,
            'label': '欠款预警',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 434,
              'label': '列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 435,
              'label': '编辑备注',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 436,
              'label': '导出欠款信息',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1063,
              'label': '打印欠款信息',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 412,
            'label': '月收款计划',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 437,
              'label': '列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 438,
              'label': '添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 439,
              'label': '编辑',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 440,
              'label': '删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 441,
              'label': '完成计划',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 442,
              'label': '下载收款计划',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1064,
              'label': '打印收款计划',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 1005,
            'label': '计划执行',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 1006,
              'label': '收款计划执行列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1007,
              'label': '下载',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1065,
              'label': '打印',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 413,
            'label': '开票与收款',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 453,
              'label': '结算',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 443,
              'label': '收款列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 444,
              'label': '收款添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 445,
              'label': '收款编辑',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 446,
              'label': '收款删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 447,
              'label': '收款明细(下载)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1061,
              'label': '收款明细(打印)',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 448,
              'label': '开票列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 449,
              'label': '开票添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 450,
              'label': '开票编辑',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 451,
              'label': '开票删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 624,
              'label': '开票办理',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 452,
              'label': '开票信息(下载)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1062,
              'label': '开票明细(打印)',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 1274,
            'label': '发运信息',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 1277,
              'label': '列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1278,
              'label': '打印',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 1290,
            'label': '项目执行台账',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 1291,
              'label': '项目台账列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1292,
              'label': '打印项目台账',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1293,
              'label': '项目台账数据明细',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1294,
              'label': '打印项目台账数据明细',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }]
          }]
        }, {
          'id': 614,
          'label': '报销管理',
          'own': null,
          'permissionTypeId': null,
          'type': 1,
          'children': [{
            'id': 615,
            'label': '报销列表',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 625,
              'label': '报销列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1066,
              'label': '打印报销明细',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1034,
              'label': '报销添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1348,
              'label': '报销编辑',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1349,
              'label': '报销删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 626,
              'label': '报销办理(OA)',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 627,
              'label': '下载报销信息',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }]
          }]
        }, {
          'id': 616,
          'label': '物料供应商付款管理',
          'own': null,
          'permissionTypeId': null,
          'type': 1,
          'children': [{
            'id': 617,
            'label': '订单列表',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 628,
              'label': '订单列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 629,
              'label': '订单信息',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 638,
              'label': '订单结算',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 630,
              'label': '收货信息',
              'own': null,
              'permissionTypeId': 4,
              'type': 2,
              'children': null
            }, {
              'id': 632,
              'label': '付款列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1038,
              'label': '付款添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1123,
              'label': '付款编辑',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1124,
              'label': '付款删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 633,
              'label': '付款办理(OA)',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 634,
              'label': '付款明细(下载)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1067,
              'label': '付款明细(打印)',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 636,
              'label': '收票列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1037,
              'label': '收票添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1125,
              'label': '收票删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 635,
              'label': '收票办理(OA)',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 637,
              'label': '收票明细(下载)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1068,
              'label': '收票明细(打印)',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 619,
            'label': '应付汇总',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 639,
              'label': '应付列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 640,
              'label': '应付列表下载',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1069,
              'label': '打印供应商对账单',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }]
          }]
        }, {
          'id': 620,
          'label': '物流供应商付款管理',
          'own': null,
          'permissionTypeId': null,
          'type': 1,
          'children': [{
            'id': 621,
            'label': '物料运输订单',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 641,
              'label': '订单列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 642,
              'label': '订单信息',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 651,
              'label': '订单结算',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 643,
              'label': '收货信息',
              'own': null,
              'permissionTypeId': 4,
              'type': 2,
              'children': null
            }, {
              'id': 645,
              'label': '付款列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1036,
              'label': '付款添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1120,
              'label': '付款编辑',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1121,
              'label': '付款删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 646,
              'label': '付款办理(OA)',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 647,
              'label': '付款明细(下载)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1070,
              'label': '付款明细(打印)',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 648,
              'label': '收票列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1035,
              'label': '收票添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1122,
              'label': '收票删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 649,
              'label': '收票办理(OA)',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 650,
              'label': '收票明细(下载)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1071,
              'label': '收票明细(打印)',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 1191,
            'label': '制成品运输订单',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 1192,
              'label': '订单列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1193,
              'label': '收货信息（所有操作）',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1194,
              'label': '付款列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1195,
              'label': '付款添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1196,
              'label': '付款编辑',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1197,
              'label': '付款删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1198,
              'label': '付款办理(OA)',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1199,
              'label': '付款明细(下载)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1200,
              'label': '付款明细(打印)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1201,
              'label': '收票列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1202,
              'label': '收票添加',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1203,
              'label': '收票删除',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1204,
              'label': '收票办理(OA)',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }, {
              'id': 1205,
              'label': '收票明细(下载)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1206,
              'label': '收票明细(打印)',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1207,
              'label': '结算',
              'own': null,
              'permissionTypeId': 2,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 623,
            'label': '应付汇总',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 652,
              'label': '应付列表',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 653,
              'label': '应付列表下载',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1072,
              'label': '打印供应商对账单',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }]
          }]
        }, {
          'id': 1001,
          'label': '成本中心',
          'own': null,
          'permissionTypeId': null,
          'type': 1,
          'children': [{
            'id': 1002,
            'label': '项目财报',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 1009,
              'label': '项目财报',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1010,
              'label': '项目财报下载',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1288,
              'label': '项目财报分类详情',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1289,
              'label': '打印项目财报分类',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 1003,
            'label': '辅材摊销',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 1011,
              'label': '辅材消耗月度汇总',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1012,
              'label': '辅材消耗分析',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }, {
              'id': 1013,
              'label': '项目摊销',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }]
          }, {
            'id': 1004,
            'label': '生产产量',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 1014,
              'label': '辅材成本下载',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }, {
              'id': 1015,
              'label': '工厂生产产量',
              'own': null,
              'permissionTypeId': 3,
              'type': 2,
              'children': null
            }]
          }]
        }]
      }, {
        'id': 1377,
        'label': '计划管理',
        'own': null,
        'permissionTypeId': null,
        'type': 0,
        'children': [{
          'id': 1378,
          'label': '项目列表',
          'own': null,
          'permissionTypeId': null,
          'type': 1,
          'children': [{
            'id': 1379,
            'label': '我的项目',
            'own': null,
            'permissionTypeId': null,
            'type': 1,
            'children': [{
              'id': 1380,
              'label': '列表信息',
              'own': null,
              'permissionTypeId': 1,
              'type': 2,
              'children': null
            }]
          }]
        }]
      }]
    }
  }
}
export default [
  getMenu,
  addMenu,
  editMenu,
  delMenu,
  getMenuTree
]
